### PR TITLE
fix app icon to fit in the app dropdown style

### PR DESCRIPTION
**Pull request by jancborchardt**
The actual correct pull request to this repo, see original at https://github.com/jancborchardt/owncloud-spreedme/pull/1

This way it is actually better visible and the blue doesn’t battle for attention with the Nextcloud blue.

Before & after:
spreedmenu-before spreedmenu-after

Please review @karlitschek @leonklingele

Btw – should we rename this repo and such to »nextcloud-spreedme«?

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1: and yes. we should rename the repo

**Comment by fancycode** [comment]
Thanks, I like it :+1:

@longsleep is currently working on renaming the various packages / repos, so he should also take care of renaming this repo. Most likely requires some additional work for packaging / automatic upgrades.

@vaneslie what do you think about the icon changes?

**Comment by vaneslie** [comment]
@fancycode Fine by me (and Niels) 👍

**Comment by longsleep** [comment]
@leonklingele - will you take care about renaming this repository? This should go together with the rest of the ownCloud to Nextcloud changes.

**Pull request merged**
